# Generated by Django 5.2.3 on 2025-06-25 06:48

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_prenom",
                    models.CharField(max_length=200, verbose_name="Nom et Prénom"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Adresse e-mail"),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Numéro de téléphone"
                    ),
                ),
                ("sujet", models.CharField(max_length=200, verbose_name="Sujet")),
                ("message", models.TextField(verbose_name="Message")),
                ("is_read", models.BooleanField(default=False, verbose_name="Lu")),
                (
                    "is_replied",
                    models.BooleanField(default=False, verbose_name="Répondu"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Message de contact",
                "verbose_name_plural": "Messages de contact",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_fr",
                    models.CharField(max_length=200, verbose_name="Titre (Français)"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=200, verbose_name="Titre (Anglais)"),
                ),
                (
                    "description_fr",
                    ckeditor.fields.RichTextField(
                        verbose_name="Description (Français)"
                    ),
                ),
                (
                    "description_en",
                    ckeditor.fields.RichTextField(verbose_name="Description (Anglais)"),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="events/"),
                ),
                (
                    "date_event",
                    models.DateTimeField(verbose_name="Date et heure de l'événement"),
                ),
                ("location", models.CharField(max_length=200, verbose_name="Lieu")),
                (
                    "max_participants",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Nombre maximum de participants",
                    ),
                ),
                (
                    "registration_deadline",
                    models.DateTimeField(verbose_name="Date limite d'inscription"),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, verbose_name="Événement en vedette"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Événement",
                "verbose_name_plural": "Événements",
                "ordering": ["date_event"],
            },
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_fr",
                    models.CharField(max_length=200, verbose_name="Titre (Français)"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=200, verbose_name="Titre (Anglais)"),
                ),
                (
                    "description_fr",
                    models.TextField(blank=True, verbose_name="Description (Français)"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="Description (Anglais)"),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Vidéo")],
                        default="image",
                        max_length=10,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="gallery/images/"
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL de la vidéo"
                    ),
                ),
                (
                    "video_file",
                    models.FileField(
                        blank=True, null=True, upload_to="gallery/videos/"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="En vedette"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Élément de galerie",
                "verbose_name_plural": "Galerie",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_fr",
                    models.CharField(max_length=200, verbose_name="Titre (Français)"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=200, verbose_name="Titre (Anglais)"),
                ),
                (
                    "description_fr",
                    ckeditor.fields.RichTextField(
                        verbose_name="Description (Français)"
                    ),
                ),
                (
                    "description_en",
                    ckeditor.fields.RichTextField(verbose_name="Description (Anglais)"),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="projects/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "En planification"),
                            ("ongoing", "En cours"),
                            ("completed", "Terminé"),
                            ("suspended", "Suspendu"),
                        ],
                        default="planning",
                        max_length=20,
                    ),
                ),
                (
                    "budget_required",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Budget requis (FCFA)",
                    ),
                ),
                (
                    "budget_collected",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Budget collecté (FCFA)",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Date de début")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="Date de fin"),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, verbose_name="Projet en vedette"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Projet",
                "verbose_name_plural": "Projets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(default="A²ELBM2", max_length=200)),
                (
                    "slogan_fr",
                    models.CharField(max_length=300, verbose_name="Slogan (Français)"),
                ),
                (
                    "slogan_en",
                    models.CharField(max_length=300, verbose_name="Slogan (Anglais)"),
                ),
                (
                    "description_fr",
                    ckeditor.fields.RichTextField(
                        verbose_name="Description de l'association (Français)"
                    ),
                ),
                (
                    "description_en",
                    ckeditor.fields.RichTextField(
                        verbose_name="Description de l'association (Anglais)"
                    ),
                ),
                (
                    "president_message_fr",
                    ckeditor.fields.RichTextField(
                        verbose_name="Message du président (Français)"
                    ),
                ),
                (
                    "president_message_en",
                    ckeditor.fields.RichTextField(
                        verbose_name="Message du président (Anglais)"
                    ),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="site/")),
                (
                    "hero_image",
                    models.ImageField(blank=True, null=True, upload_to="site/"),
                ),
                ("facebook_url", models.URLField(blank=True)),
                ("whatsapp_group_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
            ],
            options={
                "verbose_name": "Paramètres du site",
                "verbose_name_plural": "Paramètres du site",
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_prenom",
                    models.CharField(max_length=200, verbose_name="Nom et Prénom"),
                ),
                ("date_naissance", models.DateField(verbose_name="Date de naissance")),
                (
                    "lieu_naissance",
                    models.CharField(max_length=100, verbose_name="Lieu de naissance"),
                ),
                (
                    "promotion",
                    models.CharField(
                        max_length=20, verbose_name="Promotion (année de sortie)"
                    ),
                ),
                (
                    "telephone",
                    models.CharField(max_length=20, verbose_name="Numéro de téléphone"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Adresse e-mail"),
                ),
                (
                    "profession",
                    models.CharField(
                        max_length=200, verbose_name="Profession actuelle"
                    ),
                ),
                ("adresse", models.TextField(verbose_name="Adresse actuelle")),
                (
                    "member_type",
                    models.CharField(
                        choices=[
                            ("founder", "Membre Fondateur"),
                            ("bureau", "Membre du Bureau"),
                            ("conseil", "Conseiller"),
                            ("simple", "Membre Simple"),
                        ],
                        default="simple",
                        max_length=20,
                    ),
                ),
                (
                    "poste_bureau",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Poste au bureau",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="members/"),
                ),
                (
                    "bio",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Biographie"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("date_adhesion", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Membre",
                "verbose_name_plural": "Membres",
                "ordering": ["nom_prenom"],
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_fr",
                    models.CharField(max_length=200, verbose_name="Titre (Français)"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=200, verbose_name="Titre (Anglais)"),
                ),
                (
                    "content_fr",
                    ckeditor.fields.RichTextField(verbose_name="Contenu (Français)"),
                ),
                (
                    "content_en",
                    ckeditor.fields.RichTextField(verbose_name="Contenu (Anglais)"),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="news/")),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Publié"),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, verbose_name="Article en vedette"
                    ),
                ),
                (
                    "publication_date",
                    models.DateTimeField(verbose_name="Date de publication"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actualité",
                "verbose_name_plural": "Actualités",
                "ordering": ["-publication_date"],
            },
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_prenom",
                    models.CharField(max_length=200, verbose_name="Nom et Prénom"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Adresse e-mail"),
                ),
                (
                    "telephone",
                    models.CharField(max_length=20, verbose_name="Numéro de téléphone"),
                ),
                (
                    "promotion",
                    models.CharField(max_length=20, verbose_name="Promotion"),
                ),
                (
                    "message",
                    models.TextField(blank=True, verbose_name="Message/Commentaire"),
                ),
                (
                    "is_confirmed",
                    models.BooleanField(default=False, verbose_name="Confirmé"),
                ),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.event"
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscription à l'événement",
                "verbose_name_plural": "Inscriptions aux événements",
                "ordering": ["-registration_date"],
                "unique_together": {("event", "email")},
            },
        ),
    ]
