# Generated by Django 4.2.27 on 2026-01-30 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorshipSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la session')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Session active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Session de Parrainage',
                'verbose_name_plural': 'Sessions de Parrainage',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AlterField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('level', models.CharField(choices=[('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2'), ('PHD', 'Doctorat')], max_length=10, verbose_name='Niveau')),
                ('specialty', models.CharField(choices=[('DS', 'Data Science'), ('RESEAU', 'Réseau et Système'), ('SECU', 'Sécurité Informatique'), ('GL', 'Génie Logiciel')], max_length=20, verbose_name='Spécialité')),
                ('expertise_domains', models.TextField(verbose_name='Domaines de compétence (séparés par des virgules)')),
                ('max_mentees', models.IntegerField(default=2, verbose_name='Nombre max de filleuls')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sponsorshipsession', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Parrain',
                'verbose_name_plural': 'Parrains',
            },
        ),
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('level', models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3')], max_length=10, verbose_name='Niveau actuel')),
                ('desired_specialty', models.CharField(choices=[('DS', 'Data Science'), ('RESEAU', 'Réseau et Système'), ('SECU', 'Sécurité Informatique'), ('GL', 'Génie Logiciel')], max_length=20, verbose_name='Spécialité future souhaitée')),
                ('competencies', models.TextField(verbose_name='Compétences actuelles')),
                ('professional_domain_1', models.CharField(max_length=100, verbose_name='Domaine pro souhaité 1')),
                ('professional_domain_2', models.CharField(blank=True, max_length=100, verbose_name='Domaine pro souhaité 2')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.mentor', verbose_name='Parrain attribué')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sponsorshipsession', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Filleul',
                'verbose_name_plural': 'Filleuls',
            },
        ),
    ]
