# Generated by Django 4.2.27 on 2026-01-30 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sponsorshipsession_alter_member_is_active_mentor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='COMS.A.S', max_length=200),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('mentee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.mentee', verbose_name='Filleul')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mentor', verbose_name='Parrain')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sponsorshipsession', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Binôme',
                'verbose_name_plural': 'Binômes',
                'ordering': ['-created_at'],
                'unique_together': {('mentor', 'mentee')},
            },
        ),
    ]
