# Generated by Django 4.2.27 on 2026-01-31 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_sitesettings_site_name_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du concours')),
                ('slug', models.SlugField(help_text='URL conviviale (ex: miss-master-2026)', unique=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='contests/', verbose_name='Image de couverture')),
                ('start_date', models.DateTimeField(verbose_name='Date de début')),
                ('end_date', models.DateTimeField(verbose_name='Date de fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('allow_public_candidates', models.BooleanField(default=False, verbose_name='Autoriser les candidatures publiques')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Concours',
                'verbose_name_plural': 'Concours',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du candidat / Projet')),
                ('description', models.TextField(verbose_name='Bio / Description')),
                ('image', models.ImageField(upload_to='candidates/', verbose_name='Photo / Image')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Lien Vidéo (YouTube etc.)')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='approved', max_length=20, verbose_name='Statut')),
                ('votes_count', models.IntegerField(default=0, verbose_name='Nombre de votes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='main.contest', verbose_name='Concours')),
            ],
            options={
                'verbose_name': 'Candidat',
                'verbose_name_plural': 'Candidats',
                'ordering': ['-votes_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Adresse IP')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='Clé de session')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.candidate', verbose_name='Candidat')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.contest', verbose_name='Concours')),
            ],
            options={
                'verbose_name': 'Vote',
                'verbose_name_plural': 'Votes',
                'indexes': [models.Index(fields=['contest', 'ip_address', 'session_key'], name='main_vote_contest_f1021d_idx')],
            },
        ),
    ]
