# Generated by Django 4.2.27 on 2026-01-31 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_contest_candidate_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='matricule',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Matricule Étudiant'),
        ),
        migrations.AddField(
            model_name='vote',
            name='voter_email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email Votant'),
        ),
        migrations.AddField(
            model_name='vote',
            name='voter_matricule',
            field=models.CharField(default='', max_length=20, verbose_name='Matricule Votant'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('contest', 'voter_email'), name='unique_vote_email_per_contest'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('contest', 'voter_matricule'), name='unique_vote_matricule_per_contest'),
        ),
    ]
