# Generated by Django 4.2.27 on 2026-01-31 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_member_matricule_vote_voter_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentee',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='mentee',
            name='professional_domain_1',
        ),
        migrations.RemoveField(
            model_name='mentee',
            name='professional_domain_2',
        ),
        migrations.AddField(
            model_name='mentee',
            name='professional_domains',
            field=models.TextField(default='', verbose_name='Domaines pro souhaités (Liste)'),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='competencies',
            field=models.TextField(verbose_name='Compétences actuelles (Liste)'),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='desired_specialty',
            field=models.CharField(max_length=100, verbose_name='Spécialité souhaitée'),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Adresse e-mail'),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='level',
            field=models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3')], max_length=50, verbose_name="Niveau d'étude"),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.sponsorshipsession', verbose_name='Session'),
        ),
    ]
