# Generated by Django 4.2.27 on 2026-01-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_mentee_mentor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='adresse',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse actuelle'),
        ),
        migrations.AlterField(
            model_name='member',
            name='profession',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Profession actuelle'),
        ),
        migrations.AlterField(
            model_name='member',
            name='promotion',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Promotion (année de sortie)'),
        ),
    ]
