# Generated by Django 4.2.27 on 2026-01-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_member_adresse_alter_member_profession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='niveau',
            field=models.CharField(blank=True, choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('ICT-L1', 'ICT-L1'), ('ICT-L2', 'ICT-L2'), ('ICT-L3', 'ICT-L3'), ('M1', 'Master 1'), ('M2', 'Master 2'), ('PhD', 'Doctorat')], max_length=20, null=True, verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='level',
            field=models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('ICT-L1', 'ICT-L1'), ('ICT-L2', 'ICT-L2'), ('ICT-L3', 'ICT-L3'), ('M1', 'Master 1'), ('M2', 'Master 2'), ('PhD', 'Doctorat')], max_length=50, verbose_name="Niveau d'étude"),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='level',
            field=models.CharField(choices=[('L3', 'Licence 3'), ('ICT-L3', 'ICT-L3'), ('M1', 'Master 1'), ('M2', 'Master 2'), ('PHD', 'Doctorat')], max_length=10, verbose_name='Niveau'),
        ),
    ]
