# Generated by Django 4.2.27 on 2026-02-12 22:13

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_member_niveau_alter_mentee_level_alter_mentor_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la salle (ex: S001)')),
                ('capacity', models.IntegerField(blank=True, null=True, verbose_name='Capacité (places)')),
                ('location_description', ckeditor.fields.RichTextField(verbose_name='Description / Localisation')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='department/classrooms/', verbose_name='Photo de la salle')),
                ('is_lab', models.BooleanField(default=False, verbose_name='Est un laboratoire')),
            ],
            options={
                'verbose_name': 'Salle de cours',
                'verbose_name_plural': 'Salles de cours',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Delegate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('level', models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2'), ('INT-L1', 'INT-L1'), ('INT-L2', 'INT-L2'), ('INT-L3', 'INT-L3')], max_length=20, verbose_name='Niveau')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='department/delegates/', verbose_name='Photo')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone (WhatsApp)')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('year', models.CharField(default='2025-2026', max_length=9, verbose_name='Année académique (ex: 2025-2026)')),
                ('motto', models.CharField(blank=True, max_length=200, verbose_name='Devise / Citation')),
            ],
            options={
                'verbose_name': 'Délégué',
                'verbose_name_plural': 'Délégués',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('grade', models.CharField(blank=True, choices=[('Pr', 'Professeur Titulaire'), ('Mc', 'Maître de Conférences'), ('Dr', 'Chargé de cours'), ('Ass', 'Assistant'), ('Mon', 'Moniteur')], max_length=10, verbose_name='Grade')),
                ('specialty', models.CharField(blank=True, max_length=200, verbose_name='Spécialité')),
                ('office_description', ckeditor.fields.RichTextField(blank=True, verbose_name='Description/Localisation du Bureau')),
                ('office_photo', models.ImageField(blank=True, null=True, upload_to='department/offices/', verbose_name='Photo de la porte du bureau')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='department/professors/', verbose_name='Photo de profil')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email professionnel')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RequestDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du modèle')),
                ('description', models.TextField(blank=True, verbose_name='Description / Instructions')),
                ('file', models.FileField(blank=True, null=True, upload_to='requests/documents/', verbose_name='Fichier (PDF, Docx...)')),
                ('image_preview', models.ImageField(blank=True, null=True, upload_to='requests/previews/', verbose_name='Aperçu (Image)')),
                ('doc_type', models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word'), ('image', 'Image'), ('text', 'Texte')], default='pdf', max_length=10, verbose_name='Type de fichier')),
                ('downloads_count', models.IntegerField(default=0, verbose_name='Nombre de téléchargements')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Modèle de Requête',
                'verbose_name_plural': 'Modèles de Requêtes',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(help_text='URL conviviale', unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Image de couverture')),
                ('content', ckeditor.fields.RichTextField(verbose_name="Contenu de l'article")),
                ('category', models.CharField(choices=[('tuto', 'Tutoriel'), ('conseil', 'Conseil Académique'), ('stage', 'Stage & Emploi'), ('master', 'Master & Recherche'), ('vie', 'Vie Associative')], default='conseil', max_length=20, verbose_name='Catégorie')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de publication')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publié')),
                ('views_count', models.IntegerField(default=0, verbose_name='Vues')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.member', verbose_name='Auteur')),
            ],
            options={
                'verbose_name': 'Article de Blog',
                'verbose_name_plural': 'Articles de Blog',
                'ordering': ['-published_at'],
            },
        ),
    ]
