# Generated by Django 4.2.27 on 2026-02-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_classroom_delegate_professor_requestdocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='likes_count',
            field=models.IntegerField(default=0, verbose_name="J'aime"),
        ),
    ]
