# Generated by Django 4.2.27 on 2026-02-13 06:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_blogarticle_likes_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=200, verbose_name='Titre (Français)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Titre (Anglais)')),
                ('description_fr', models.TextField(blank=True, verbose_name='Description (Français)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (Anglais)')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='gallery/albums/', verbose_name='Image de couverture')),
                ('event_date', models.DateField(default=django.utils.timezone.now, verbose_name="Date de l'événement")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Album Photo',
                'verbose_name_plural': 'Albums Photos',
                'ordering': ['-event_date'],
            },
        ),
        migrations.AddField(
            model_name='gallery',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.galleryalbum', verbose_name='Album'),
        ),
    ]
