# Generated by Django 4.2.27 on 2026-02-13 06:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_galleryalbum_gallery_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='tickets/qrcodes/', verbose_name='Code QR'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='ticket_pdf',
            field=models.FileField(blank=True, null=True, upload_to='tickets/pdfs/', verbose_name='Ticket PDF'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
