# Generated by Django 4.2.27 on 2026-02-13 06:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_eventregistration_qr_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
