# Generated by Django 4.2.27 on 2026-02-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_eventregistration_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='certificate_pdf',
            field=models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Attestation PDF'),
        ),
    ]
