# Generated by Django 4.2.27 on 2026-02-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_eventregistration_certificate_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='certificate_dept_head_name',
            field=models.CharField(default='Chef de département', max_length=100, verbose_name='Nom du chef de département'),
        ),
        migrations.AddField(
            model_name='event',
            name='certificate_dept_head_title',
            field=models.CharField(default='Chef de département informatique', max_length=100, verbose_name='Titre du chef de département'),
        ),
        migrations.AddField(
            model_name='event',
            name='certificate_description',
            field=models.TextField(blank=True, verbose_name="Description pour l'attestation"),
        ),
        migrations.AddField(
            model_name='event',
            name='certificate_enabled',
            field=models.BooleanField(default=True, verbose_name='Activer les attestations'),
        ),
        migrations.AddField(
            model_name='event',
            name='certificate_president_name',
            field=models.CharField(default='Président COMS.A.S', max_length=100, verbose_name='Nom du président'),
        ),
        migrations.AddField(
            model_name='event',
            name='certificate_president_title',
            field=models.CharField(default='Président du COMS.A.S', max_length=100, verbose_name='Titre du président'),
        ),
        migrations.AddField(
            model_name='event',
            name='certificate_title',
            field=models.CharField(blank=True, max_length=200, verbose_name="Titre de l'attestation"),
        ),
    ]
