# Generated by Django 4.2.27 on 2026-02-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_event_certificate_dept_head_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='badge_enabled',
            field=models.BooleanField(default=True, verbose_name='Activer les badges'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='badge_pdf',
            field=models.FileField(blank=True, null=True, upload_to='badges/', verbose_name='Badge PDF'),
        ),
    ]
