# Generated by Django 4.2.27 on 2026-02-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_event_badge_enabled_eventregistration_badge_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='photo',
            field=models.ImageField(blank=True, help_text='Photo pour le badge (optionnel)', null=True, upload_to='participants/photos/', verbose_name='Photo du participant'),
        ),
    ]
