# Generated by Django 4.2.27 on 2026-02-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_eventregistration_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du document')),
                ('description', models.TextField(blank=True, verbose_name='Description optionnelle')),
                ('file', models.FileField(upload_to='archives/%Y/%m/', verbose_name='Fichier (PDF, Image...)')),
                ('academic_year', models.CharField(default='2023-2024', help_text='Ex: 2023-2024', max_length=9, verbose_name='Année Académique')),
                ('level', models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2'), ('ICT-L1', 'ICT University - L1'), ('ICT-L2', 'ICT University - L2'), ('ICT-L3', 'ICT University - L3'), ('OTHER', 'Autre')], max_length=10, verbose_name="Niveau d'étude")),
                ('category', models.CharField(choices=[('PV', 'Procès Verbal'), ('OTHER', 'Autre Document')], default='PV', max_length=10, verbose_name='Catégorie')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
            ],
            options={
                'verbose_name': 'Archive',
                'verbose_name_plural': 'Archives',
                'ordering': ['-academic_year', '-created_at'],
            },
        ),
    ]
