# Generated by Django 4.2.27 on 2026-02-15 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='downloads_count',
            field=models.IntegerField(default=0, verbose_name='Téléchargements'),
        ),
        migrations.AddField(
            model_name='archive',
            name='likes_count',
            field=models.IntegerField(default=0, verbose_name='Likes'),
        ),
        migrations.AddField(
            model_name='archive',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug URL'),
        ),
        migrations.AddField(
            model_name='archive',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='Vues'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='level',
            field=models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2'), ('ICT-L1', 'ICT-L1'), ('ICT-L2', 'ICT-L2'), ('ICT-L3', 'ICT-L3'), ('OTHER', 'Autre')], max_length=10, verbose_name="Niveau d'étude"),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='level',
            field=models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2'), ('ICT-L1', 'ICT-L1'), ('ICT-L2', 'ICT-L2'), ('ICT-L3', 'ICT-L3')], max_length=20, verbose_name='Niveau'),
        ),
        migrations.CreateModel(
            name='ArchiveComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(default='Anonyme', max_length=100, verbose_name='Nom complet')),
                ('content', models.TextField(verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.archive', verbose_name='Archive')),
            ],
            options={
                'verbose_name': 'Commentaire Archive',
                'verbose_name_plural': 'Commentaires Archives',
                'ordering': ['-created_at'],
            },
        ),
    ]
