# Generated by Django 4.2.27 on 2026-02-28 12:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_archive_downloads_count_archive_likes_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastPresident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom et Prénom')),
                ('mandate_start', models.PositiveIntegerField(help_text='Ex: 2018', verbose_name='Année de début de mandat')),
                ('mandate_end', models.PositiveIntegerField(blank=True, help_text='Ex: 2019', null=True, verbose_name='Année de fin de mandat')),
                ('current_function', models.CharField(blank=True, help_text='Ex: Ingénieur Logiciel chez Google', max_length=200, null=True, verbose_name='Fonction actuelle')),
                ('bio', ckeditor.fields.RichTextField(verbose_name='Biographie / Mot du Président')),
                ('photo', models.ImageField(upload_to='presidents/', verbose_name='Photo de Profil')),
                ('is_current', models.BooleanField(default=False, verbose_name='Est le président actuel ?')),
                ('facebook_link', models.URLField(blank=True, null=True, verbose_name='Lien Facebook')),
                ('linkedin_link', models.URLField(blank=True, null=True, verbose_name='Lien LinkedIn')),
                ('twitter_link', models.URLField(blank=True, null=True, verbose_name='Lien Twitter/X')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Président',
                'verbose_name_plural': 'Présidents',
                'ordering': ['-mandate_start'],
            },
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-created_at'], 'verbose_name': 'Média interactif', 'verbose_name_plural': 'Médias interactifs'},
        ),
    ]
