# Generated by Django 4.2.27 on 2026-03-14 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_pastpresident_alter_gallery_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='JUINCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la commission')),
                ('code', models.CharField(max_length=30, verbose_name='Code (ex: CELLCOM-JUIN)')),
                ('description', models.TextField(verbose_name='Description / Mission')),
                ('icon', models.CharField(choices=[('fa-bullhorn', 'Communication'), ('fa-microphone', 'Conférences'), ('fa-laptop-code', 'Projets & Innovations'), ('fa-handshake', 'Partenariats'), ('fa-paint-brush', 'Design & Infographie'), ('fa-truck', 'Logistique'), ('fa-shield-alt', 'Protocole'), ('fa-utensils', 'Gastronomie'), ('fa-music', 'Animation & Divertissement'), ('fa-glass-cheers', 'Soirée de Gala')], default='fa-bullhorn', max_length=50, verbose_name='Icône FontAwesome')),
                ('color', models.CharField(default='primary', max_length=20, verbose_name='Couleur Bootstrap (primary, success…)')),
                ('chef_nom', models.CharField(blank=True, max_length=200, verbose_name='Nom du/de la Chef·fe')),
                ('chef_contact', models.CharField(blank=True, max_length=100, verbose_name='Contact Chef·fe')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Commission J.U.IN',
                'verbose_name_plural': 'Commissions J.U.IN',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JUINEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition_number', models.PositiveIntegerField(default=20, verbose_name="Numéro d'édition")),
                ('title', models.CharField(max_length=300, verbose_name="Titre de l'édition")),
                ('theme', models.CharField(max_length=500, verbose_name='Thème')),
                ('slogan', models.CharField(default='Coder • Innover • Entreprendre', max_length=200, verbose_name='Slogan')),
                ('description', models.TextField(verbose_name='Description / Argumentaire scientifique')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('location', models.CharField(default='Campus UY1 — Esplanade extension 1', max_length=300, verbose_name='Lieu')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='juin/covers/', verbose_name='Image de couverture')),
                ('is_active', models.BooleanField(default=True, verbose_name='Édition active (courante)')),
                ('applications_open', models.BooleanField(default=True, verbose_name='Inscriptions aux commissions ouvertes')),
                ('donations_open', models.BooleanField(default=True, verbose_name='Dons ouverts')),
                ('president_name', models.CharField(default='MFENJOU ANAS CHERIF', max_length=200, verbose_name='Président du comité')),
                ('president_contact', models.CharField(blank=True, max_length=50, verbose_name='Contact président')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Édition J.U.IN',
                'verbose_name_plural': 'Éditions J.U.IN',
                'ordering': ['-edition_number'],
            },
        ),
        migrations.CreateModel(
            name='JUINDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.CharField(max_length=200, verbose_name='Nom du donateur')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email (optionnel)')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Montant (FCFA)')),
                ('type_paiement', models.CharField(choices=[('mtn', 'MTN Mobile Money'), ('orange', 'Orange Money'), ('cb', 'Carte Bancaire'), ('especes', 'Espèces'), ('autre', 'Autre')], default='mtn', max_length=20, verbose_name='Mode de paiement')),
                ('message', models.CharField(blank=True, max_length=300, verbose_name='Message public (optionnel)')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Afficher anonymement')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Don confirmé/reçu')),
                ('date_don', models.DateTimeField(auto_now_add=True, verbose_name='Date du don')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='main.juinedition', verbose_name='Édition')),
            ],
            options={
                'verbose_name': 'Don J.U.IN',
                'verbose_name_plural': 'Dons J.U.IN',
                'ordering': ['-date_don'],
            },
        ),
        migrations.CreateModel(
            name='JUINCommissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.CharField(max_length=200, verbose_name='Nom et Prénom')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse e-mail')),
                ('telephone', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('etablissement', models.CharField(choices=[('UY1-INFO', 'UY1 — Département Informatique (COM.S.AS)'), ('ENSPY', 'ENSPY — École Nationale Supérieure Polytechnique'), ('STJEAN', 'Institut Saint-Jean'), ('SUPPTIC', "SUP'PTIC"), ('OTHER', 'Autre établissement')], max_length=20, verbose_name='Établissement')),
                ('niveau', models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('ICT-L1', 'ICT-L1'), ('ICT-L2', 'ICT-L2'), ('ICT-L3', 'ICT-L3'), ('M1', 'Master 1'), ('M2', 'Master 2'), ('PhD', 'Doctorat'), ('OTHER', 'Autre')], max_length=20, verbose_name="Niveau d'études")),
                ('photo', models.ImageField(blank=True, null=True, upload_to='juin/applicants/', verbose_name='Photo (portrait)')),
                ('motivation', models.TextField(blank=True, verbose_name='Message de motivation')),
                ('statut', models.CharField(choices=[('pending', '⏳ En attente'), ('approved', '✅ Approuvé'), ('rejected', '❌ Rejeté')], default='pending', max_length=20, verbose_name='Statut')),
                ('commission_role', models.CharField(choices=[('president', 'Président(e)'), ('vice_president', 'Vice-Président(e)'), ('rapporteur', 'Rapporteur(e) Principal(e)'), ('rapporteur_adj', 'Rapporteur(e) Adjoint(e)'), ('membre', 'Membre')], default='membre', max_length=20, verbose_name='Rôle dans la commission')),
                ('date_postulation', models.DateTimeField(auto_now_add=True, verbose_name='Date de candidature')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('motif_rejet', models.TextField(blank=True, verbose_name='Motif du rejet (si rejeté)')),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='main.juincommission', verbose_name='Commission souhaitée')),
            ],
            options={
                'verbose_name': 'Candidature Commission J.U.IN',
                'verbose_name_plural': 'Candidatures Commissions J.U.IN',
                'ordering': ['-date_postulation'],
            },
        ),
        migrations.AddField(
            model_name='juincommission',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='main.juinedition', verbose_name='Édition'),
        ),
        migrations.CreateModel(
            name='JUINActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name="Titre de l'activité")),
                ('description', models.TextField(verbose_name='Description')),
                ('activity_type', models.CharField(choices=[('conference', 'Conférence'), ('hackathon', 'Hackathon'), ('atelier', 'Atelier pratique'), ('exposition', 'Exposition de projets'), ('pitch', 'Concours de Pitch'), ('gala', 'Soirée de Gala'), ('ceremonie', 'Cérémonie officielle'), ('autre', 'Autre')], default='conference', max_length=20, verbose_name='Type')),
                ('date_activity', models.DateTimeField(verbose_name='Date et heure')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Salle / Lieu')),
                ('speaker', models.CharField(blank=True, max_length=200, verbose_name='Intervenant(s)')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='juin/activities/', verbose_name='Photo / Affiche')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Activité phare')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='main.juinedition', verbose_name='Édition')),
                ('gallery_album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juin_activities', to='main.galleryalbum', verbose_name='Album galerie lié')),
            ],
            options={
                'verbose_name': 'Activité J.U.IN',
                'verbose_name_plural': 'Activités J.U.IN',
                'ordering': ['date_activity', 'order'],
            },
        ),
    ]
