# Generated by Django 4.2.27 on 2026-03-14 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_juin_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='juindonation',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID externe (UUID)'),
        ),
        migrations.AddField(
            model_name='juindonation',
            name='freemopay_reference',
            field=models.CharField(blank=True, max_length=200, verbose_name='Référence FreemoPay'),
        ),
        migrations.AddField(
            model_name='juindonation',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('initiated', 'Initié — en cours'), ('completed', 'Payé ✅'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut paiement'),
        ),
        migrations.AddField(
            model_name='juindonation',
            name='telephone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Téléphone Mobile Money'),
        ),
        migrations.CreateModel(
            name='JUINSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name="Nom de l'entreprise / institution")),
                ('logo', models.ImageField(blank=True, null=True, upload_to='juin/sponsors/', verbose_name='Logo')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('tier', models.CharField(choices=[('gold', '🥇 Sponsor Or (500 000 F+)'), ('silver', '🥈 Sponsor Argent (200 000 F+)'), ('bronze', '🥉 Sponsor Bronze (100 000 F+)'), ('partner', '🤝 Partenaire Technique'), ('institution', '🏛️ Institution / Soutien académique'), ('media', '📺 Partenaire Médias')], default='bronze', max_length=20, verbose_name='Niveau de partenariat')),
                ('contact_name', models.CharField(max_length=200, verbose_name='Nom du responsable')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email de contact')),
                ('contact_phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('description', models.TextField(blank=True, verbose_name='Description / offre de partenariat')),
                ('contribution', models.CharField(blank=True, max_length=500, verbose_name='Contribution proposée (financière, matérielle, services...)')),
                ('statut', models.CharField(choices=[('pending', '⏳ Demande en attente'), ('approved', '✅ Approuvé — visible'), ('rejected', '❌ Refusé')], default='pending', max_length=20, verbose_name='Statut')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mettre en avant')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notes internes (admin)')),
                ('date_demande', models.DateTimeField(auto_now_add=True, verbose_name='Date de la demande')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='main.juinedition', verbose_name='Édition')),
            ],
            options={
                'verbose_name': 'Sponsor / Partenaire J.U.IN',
                'verbose_name_plural': 'Sponsors / Partenaires J.U.IN',
                'ordering': ['order', 'tier', 'company_name'],
            },
        ),
    ]
