# Generated by Django 4.2.27 on 2026-03-14 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_juin_sponsor_freemopay'),
    ]

    operations = [
        migrations.CreateModel(
            name='JUINCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la compétition')),
                ('slug', models.SlugField(blank=True, help_text='Laissé vide, sera généré automatiquement', null=True)),
                ('comp_type', models.CharField(choices=[('computer', '💻 Informatique (Hackathon, Pitch, Cyber...)'), ('sport', '⚽ Sportive (Football, Basketball, Handball...)'), ('gaming', '🎮 E-Sport / Gaming'), ('other', 'Autre')], default='computer', max_length=20, verbose_name='Type')),
                ('description', models.TextField(verbose_name='Description')),
                ('rules', models.TextField(blank=True, verbose_name="Règles / Conditions d'admission")),
                ('image', models.ImageField(blank=True, null=True, upload_to='juin/competitions/', verbose_name='Image illustrative')),
                ('max_teams', models.PositiveIntegerField(default=16, verbose_name="Nombre maximum d'équipes")),
                ('is_open', models.BooleanField(default=True, verbose_name='Inscriptions ouvertes')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Date et heure de début')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='main.juinedition', verbose_name='Édition')),
            ],
            options={
                'verbose_name': 'Compétition J.U.IN',
                'verbose_name_plural': 'Compétitions J.U.IN',
            },
        ),
        migrations.AlterField(
            model_name='juinactivity',
            name='activity_type',
            field=models.CharField(choices=[('conference', 'Conférence / Séminaire'), ('hackathon', 'Hackathon / Challenge'), ('atelier', 'Atelier pratique'), ('exposition', 'Exposition de projets'), ('pitch', 'Concours de Pitch'), ('sport', 'Activité Sportive (Foot, Basket...)'), ('gala', 'Soirée de Gala'), ('ceremonie', 'Cérémonie officielle'), ('autre', 'Autre')], default='conference', max_length=20, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='JUINTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'équipe")),
                ('captain_name', models.CharField(max_length=200, verbose_name='Nom du Capitaine / Responsable')),
                ('captain_phone', models.CharField(max_length=30, verbose_name='Téléphone (WhatsApp)')),
                ('captain_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('members_count', models.PositiveIntegerField(default=1, verbose_name='Nombre de membres')),
                ('members_list', models.TextField(help_text='Un par ligne', verbose_name='Liste des membres (Noms & Prénoms)')),
                ('project_title', models.CharField(blank=True, max_length=200, verbose_name='Titre du projet (si informatique)')),
                ('project_description', models.TextField(blank=True, verbose_name='Description du projet / Composition équipe')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='juin/teams/', verbose_name="Logo ou Photo d'équipe")),
                ('statut', models.CharField(choices=[('pending', '⏳ En attente'), ('approved', '✅ Validée'), ('rejected', '❌ Refusée')], default='pending', max_length=20, verbose_name='Statut')),
                ('date_registration', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='main.juincompetition', verbose_name='Compétition')),
            ],
            options={
                'verbose_name': 'Équipe / Candidat J.U.IN',
                'verbose_name_plural': 'Équipes / Candidats J.U.IN',
                'ordering': ['-date_registration'],
            },
        ),
    ]
