# Generated by Django 4.2.27 on 2026-03-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_juincompetition_alter_juinactivity_activity_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='juincommission',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
