# Generated by Django 4.2.27 on 2026-03-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_juincommission_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juincompetition',
            name='slug',
            field=models.SlugField(blank=True, help_text='Laissé vide, sera généré automatiquement'),
        ),
    ]
