# Generated by Django 4.2.27 on 2026-04-01 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_juincompetition_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom de la direction')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description / Missions')),
                ('icon', models.CharField(default='fa-folder', max_length=50, verbose_name='Icône FontAwesome')),
            ],
            options={
                'verbose_name': 'Direction du Club',
                'verbose_name_plural': 'Directions du Club',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200, verbose_name='Nom du projet')),
                ('description', models.TextField(verbose_name='Description du projet')),
                ('domain', models.CharField(max_length=100, verbose_name='Domaine / Secteur')),
                ('presentation_time', models.CharField(max_length=100, verbose_name='Heure de disponibilité pour présentation')),
                ('status', models.CharField(choices=[('idea', 'Idée'), ('prototype', 'Prototype'), ('final', 'Finalisé'), ('market', 'Déjà sur le marché')], default='idea', max_length=20, verbose_name="État d'avancement")),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Informations complémentaires')),
                ('submitter_name', models.CharField(max_length=200, verbose_name='Nom du porteur')),
                ('submitter_email', models.EmailField(max_length=254, verbose_name='Email de contact')),
                ('submitter_tel', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('is_reviewed', models.BooleanField(default=False, verbose_name="Revu par l'admin")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Soumission de Projet',
                'verbose_name_plural': 'Soumissions de Projets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='member',
            name='github_url',
            field=models.URLField(blank=True, null=True, verbose_name='Lien GitHub'),
        ),
        migrations.AddField(
            model_name='member',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, verbose_name='Lien LinkedIn'),
        ),
        migrations.AddField(
            model_name='member',
            name='portfolio_enabled',
            field=models.BooleanField(default=True, verbose_name='Activer le portfolio'),
        ),
        migrations.AddField(
            model_name='member',
            name='portfolio_slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug Portfolio'),
        ),
        migrations.AddField(
            model_name='member',
            name='skills',
            field=models.TextField(blank=True, help_text='Séparez par des virgules', null=True, verbose_name='Compétences'),
        ),
        migrations.AddField(
            model_name='member',
            name='twitter_url',
            field=models.URLField(blank=True, null=True, verbose_name='Lien Twitter/X'),
        ),
        migrations.AddField(
            model_name='member',
            name='website_url',
            field=models.URLField(blank=True, null=True, verbose_name='Site Web personnel'),
        ),
        migrations.CreateModel(
            name='ClubCommissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.CharField(max_length=200, verbose_name='Nom et Prénom')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse e-mail')),
                ('telephone', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('niveau', models.CharField(max_length=50, verbose_name="Niveau d'étude")),
                ('photo', models.ImageField(upload_to='club/applications/', verbose_name='Photo portrait')),
                ('motivation', models.TextField(verbose_name='Motivation')),
                ('role_applied', models.CharField(choices=[('director', 'Directeur(trice)'), ('deputy_director', 'Directeur(trice) Adjoint(e)'), ('rapporteur', 'Rapporteur(e)'), ('deputy_rapporteur', 'Rapporteur(e) Adjoint(e)'), ('member', 'Membre Simple')], default='member', max_length=30, verbose_name='Poste souhaité')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='main.clubcommission', verbose_name='Direction')),
            ],
            options={
                'verbose_name': 'Candidature Direction Club',
                'verbose_name_plural': 'Candidatures Directions Club',
                'ordering': ['-created_at'],
            },
        ),
    ]
