# Generated by Django 4.2.27 on 2026-04-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_clubcommission_projectsubmission_member_github_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegate',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Biographie / Message'),
        ),
        migrations.AddField(
            model_name='delegate',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='Lien Facebook'),
        ),
        migrations.AddField(
            model_name='delegate',
            name='github_url',
            field=models.URLField(blank=True, null=True, verbose_name='Lien GitHub'),
        ),
        migrations.AddField(
            model_name='delegate',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, verbose_name='Lien LinkedIn'),
        ),
        migrations.AddField(
            model_name='delegate',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
