# Generated by Django 4.2.27 on 2026-04-02 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_delegate_bio_delegate_facebook_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gallery_album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='main.galleryalbum', verbose_name='Album galerie lié'),
        ),
    ]
