# Generated by Django 4.2.27 on 2026-04-02 07:31

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_event_gallery_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Intitulé du poste')),
                ('company', models.CharField(max_length=150, verbose_name='Entreprise')),
                ('location', models.CharField(max_length=150, verbose_name='Localisation')),
                ('offer_type', models.CharField(choices=[('stage_acad', 'Stage Académique'), ('stage_pro', 'Stage Professionnel'), ('emploi', 'Emploi (CDD/CDI)'), ('freelance', 'Mission Freelance / Projet')], max_length=20, verbose_name='Type de contrat')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description et missions')),
                ('requirements', models.TextField(blank=True, help_text='Technologies, compétences, etc.', verbose_name='Pré-requis / Profil recherché')),
                ('apply_link', models.CharField(max_length=255, verbose_name='Lien ou Email pour postuler')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Date limite de candidature')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approuvé pour publication')),
                ('is_active', models.BooleanField(default=True, verbose_name='Offre ouverte')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.member', verbose_name='Partagé par (Membre/Alumni)')),
            ],
            options={
                'verbose_name': 'Offre Pro (Alumni)',
                'verbose_name_plural': 'Offres Pro (Alumni/Partenaires)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AcademicResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la ressource')),
                ('resource_type', models.CharField(choices=[('exam', 'Ancienne Épreuve'), ('tutorial', 'Tutoriel / Guide'), ('course', 'Support de Cours'), ('td', 'Fiche de TD/TP'), ('other', 'Autre')], max_length=20, verbose_name='Type de document')),
                ('niveau', models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('ICT-L1', 'ICT4D L1'), ('ICT-L2', 'ICT4D L2'), ('ICT-L3', 'ICT4D L3'), ('M1', 'Master 1'), ('M2', 'Master 2')], max_length=50, verbose_name="Niveau d'études")),
                ('subject', models.CharField(max_length=100, verbose_name="Matière / Unité d'enseignement")),
                ('description', models.TextField(blank=True, help_text='Facultatif', verbose_name='Description brève')),
                ('file', models.FileField(upload_to='academic_resources/', verbose_name='Document (PDF/ZIP/DOC)')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approuvé pour publication')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.member', verbose_name='Partagé par')),
            ],
            options={
                'verbose_name': 'Ressource Académique',
                'verbose_name_plural': 'Ressources Académiques',
                'ordering': ['-created_at'],
            },
        ),
    ]
