# Generated by Django 4.2.27 on 2026-04-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_joboffer_academicresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsubmission',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='projects/logos/', verbose_name='Logo du projet'),
        ),
    ]
