# Generated by Django 4.2.27 on 2026-04-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_projectsubmission_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='needs',
            field=models.TextField(blank=True, help_text='Ex: Recherche de stage, Mentorat technique, Emploi', null=True, verbose_name='Besoins'),
        ),
        migrations.AddField(
            model_name='member',
            name='other_roles',
            field=models.TextField(blank=True, help_text='Ex: Designer, Rédacteur web, Graphiste', null=True, verbose_name='Autres casquettes'),
        ),
        migrations.AddField(
            model_name='member',
            name='technologies',
            field=models.TextField(blank=True, help_text='Ex: Python, React, PostgreSQL', null=True, verbose_name='Technologies maîtrisées'),
        ),
    ]
