# Generated by Django 4.2.27 on 2026-04-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_member_needs_member_other_roles_member_technologies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubcommission',
            name='icon',
            field=models.CharField(default='fas fa-folder', max_length=255, verbose_name='Icône FontAwesome'),
        ),
        migrations.AlterField(
            model_name='clubcommission',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Slug'),
        ),
    ]
