# Generated by Django 4.2.27 on 2026-04-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_member_date_naissance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['-created_at'], 'verbose_name': 'Vote', 'verbose_name_plural': 'Votes'},
        ),
        migrations.RemoveConstraint(
            model_name='vote',
            name='unique_vote_email_per_contest',
        ),
        migrations.RemoveConstraint(
            model_name='vote',
            name='unique_vote_matricule_per_contest',
        ),
        migrations.AddField(
            model_name='candidate',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Revenus générés (FCFA)'),
        ),
        migrations.AddField(
            model_name='vote',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant payé (FCFA)'),
        ),
        migrations.AddField(
            model_name='vote',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de confirmation'),
        ),
        migrations.AddField(
            model_name='vote',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence Paiement'),
        ),
        migrations.AddField(
            model_name='vote',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Confirmé'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='vote',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID Transaction'),
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_count',
            field=models.IntegerField(default=1, verbose_name='Nombre de voix'),
        ),
        migrations.AddField(
            model_name='vote',
            name='voter_phone',
            field=models.CharField(default='', max_length=20, verbose_name='Téléphone Votant'),
        ),
        migrations.AddField(
            model_name='vote',
            name='withdrawal_reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence Retrait'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voter_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email Votant'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voter_matricule',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Matricule Votant'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['transaction_id'], name='main_vote_transac_72ea70_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['payment_reference'], name='main_vote_payment_78550d_idx'),
        ),
    ]
