# Generated by Django 4.2.27 on 2026-04-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_vote_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='certificate_main_text',
            field=models.TextField(blank=True, help_text="Texte central de l'attestation. Laissez vide pour utiliser le texte par défaut.", verbose_name='Texte principal personnalisé'),
        ),
        migrations.AddField(
            model_name='event',
            name='certificates_sent',
            field=models.BooleanField(default=False, verbose_name='Attestations envoyées par mail'),
        ),
        migrations.AddField(
            model_name='event',
            name='partner_logo_1',
            field=models.ImageField(blank=True, null=True, upload_to='events/partners/', verbose_name='Logo Partenaire 1'),
        ),
        migrations.AddField(
            model_name='event',
            name='partner_logo_2',
            field=models.ImageField(blank=True, null=True, upload_to='events/partners/', verbose_name='Logo Partenaire 2'),
        ),
        migrations.AddField(
            model_name='event',
            name='partner_logo_3',
            field=models.ImageField(blank=True, null=True, upload_to='events/partners/', verbose_name='Logo Partenaire 3'),
        ),
        migrations.AddField(
            model_name='event',
            name='president_signature',
            field=models.ImageField(blank=True, null=True, upload_to='events/signatures/', verbose_name='Signature/Cachet du Président'),
        ),
    ]
