# Generated by Django 4.2.27 on 2026-04-20 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_event_certificate_main_text_event_certificates_sent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='certificate_dept_head_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='certificate_dept_head_title',
        ),
    ]
