# Generated by Django 4.2.27 on 2026-05-02 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_remove_event_certificate_dept_head_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Âge'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='candidate_type',
            field=models.CharField(blank=True, choices=[('miss', 'Miss'), ('mister', 'Mister')], max_length=20, null=True, verbose_name='Type de candidat'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='level',
            field=models.CharField(blank=True, max_length=50, verbose_name="Niveau d'étude"),
        ),
        migrations.AddField(
            model_name='candidate',
            name='school',
            field=models.CharField(blank=True, max_length=200, verbose_name='Établissement'),
        ),
        migrations.AddField(
            model_name='vote',
            name='operator',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Opérateur'),
        ),
        migrations.CreateModel(
            name='CandidateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='candidates/gallery/', verbose_name='Image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='main.candidate', verbose_name='Candidat')),
            ],
            options={
                'verbose_name': 'Image Galerie Candidat',
                'verbose_name_plural': 'Images Galerie Candidat',
                'ordering': ['order'],
            },
        ),
    ]
