# Generated by Django 4.2.27 on 2026-05-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_candidate_age_candidate_candidate_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='is_anonymous',
            field=models.BooleanField(default=False, verbose_name='Vote Anonyme'),
        ),
        migrations.AddField(
            model_name='vote',
            name='voter_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom du Votant'),
        ),
        migrations.AddField(
            model_name='vote',
            name='voter_school',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Établissement du Votant'),
        ),
    ]
