# Generated by Django 4.2.27 on 2026-05-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_vote_is_anonymous_vote_voter_name_vote_voter_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone'),
        ),
    ]
