# Generated by Django 4.2.27 on 2026-05-13 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_candidate_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='JUINCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('candidate_type', models.CharField(choices=[('miss', 'Miss'), ('mister', 'Mister')], max_length=20, verbose_name='Type de candidat')),
                ('age', models.PositiveIntegerField(verbose_name='Âge')),
                ('level', models.CharField(max_length=50, verbose_name="Niveau d'étude")),
                ('school', models.CharField(choices=[('UY1', 'Université de Yaoundé I — Faculté des Sciences'), ('ENSPY', 'École Nationale Supérieure Polytechnique de Yaoundé'), ('STJEAN', 'Institut Saint-Jean'), ('SUPPTIC', "SUP'PTIC"), ('OTHER', 'Autre')], max_length=50, verbose_name='Établissement')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone (WhatsApp)')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('description', models.TextField(verbose_name='Biographie / Motivations')),
                ('image', models.ImageField(upload_to='juin/candidates/', verbose_name='Photo Principale')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Lien Vidéo Présentation')),
                ('status', models.CharField(choices=[('pending', '⏳ En attente'), ('approved', '✅ Approuvé'), ('rejected', '❌ Rejeté')], default='pending', max_length=20, verbose_name='Statut')),
                ('votes_count', models.IntegerField(default=0, verbose_name='Nombre de votes')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Revenus générés (FCFA)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='main.juinedition', verbose_name='Édition')),
            ],
            options={
                'verbose_name': 'Candidat(e) Miss/Mister J.U.IN',
                'verbose_name_plural': 'Candidats Miss/Mister J.U.IN',
                'ordering': ['-votes_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JUINVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom du Votant')),
                ('voter_phone', models.CharField(max_length=20, verbose_name='Téléphone Votant')),
                ('voter_school', models.CharField(blank=True, max_length=200, null=True, verbose_name='Établissement du Votant')),
                ('operator', models.CharField(blank=True, max_length=20, null=True, verbose_name='Opérateur')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Vote Anonyme')),
                ('vote_count', models.IntegerField(default=1, verbose_name='Nombre de voix')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant payé (FCFA)')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID Transaction')),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence Paiement')),
                ('withdrawal_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence Retrait')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Confirmé ✅'), ('failed', 'Échoué ❌'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de confirmation')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='main.juincandidate', verbose_name='Candidat')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.juinedition', verbose_name='Édition')),
            ],
            options={
                'verbose_name': 'Vote Miss/Mister J.U.IN',
                'verbose_name_plural': 'Votes Miss/Mister J.U.IN',
                'ordering': ['-created_at'],
            },
        ),
    ]
