# Generated by Django 4.2.30 on 2026-05-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_juincandidate_juinvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='juincandidate',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='juin/candidates/gallery/', verbose_name='Photo 2 (Galerie)'),
        ),
        migrations.AddField(
            model_name='juincandidate',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='juin/candidates/gallery/', verbose_name='Photo 3 (Galerie)'),
        ),
        migrations.AddField(
            model_name='juincandidate',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='juin/candidates/gallery/', verbose_name='Photo 4 (Galerie)'),
        ),
    ]
