# Generated by Django 4.2.30 on 2026-05-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_juincandidate_image2_juincandidate_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='juinedition',
            name='contest_registration_open',
            field=models.BooleanField(default=True, verbose_name='Inscriptions Miss/Mister ouvertes'),
        ),
        migrations.AddField(
            model_name='juinedition',
            name='contest_results_published',
            field=models.BooleanField(default=False, verbose_name='Publier les résultats finaux'),
        ),
        migrations.AddField(
            model_name='juinedition',
            name='contest_voting_active',
            field=models.BooleanField(default=True, verbose_name='Votes Miss/Mister actifs'),
        ),
    ]
