# Generated by Django 4.2.30 on 2026-05-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_juinedition_contest_registration_open_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='juinteam',
            name='school',
            field=models.CharField(choices=[('UY1', 'Université de Yaoundé I — Faculté des Sciences'), ('ENSPY', 'École Nationale Supérieure Polytechnique de Yaoundé'), ('STJEAN', 'Institut Saint-Jean'), ('SUPPTIC', "SUP'PTIC"), ('EBOLOWA', "Université d'Ebolowa"), ('OTHER', 'Autre')], default='UY1', max_length=50, verbose_name='Établissement'),
        ),
        migrations.AlterField(
            model_name='juincandidate',
            name='school',
            field=models.CharField(choices=[('UY1', 'Université de Yaoundé I — Faculté des Sciences'), ('ENSPY', 'École Nationale Supérieure Polytechnique de Yaoundé'), ('STJEAN', 'Institut Saint-Jean'), ('SUPPTIC', "SUP'PTIC"), ('EBOLOWA', "Université d'Ebolowa"), ('OTHER', 'Autre')], max_length=50, verbose_name='Établissement'),
        ),
    ]
