# Generated by Django 4.2.30 on 2026-05-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_juinteam_school_alter_juincandidate_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juincommissionapplication',
            name='etablissement',
            field=models.CharField(choices=[('UY1-INFO', 'UY1 — Département Informatique (COM.S.AS)'), ('ENSPY', 'ENSPY — École Nationale Supérieure Polytechnique'), ('STJEAN', 'Institut Saint-Jean'), ('SUPPTIC', "SUP'PTIC"), ('EBOLOWA', "Université d'Ebolowa"), ('OTHER', 'Autre établissement')], max_length=20, verbose_name='Établissement'),
        ),
    ]
