# Generated by Django 4.2.30 on 2026-05-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_alter_juincommissionapplication_etablissement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juincompetition',
            name='comp_type',
            field=models.CharField(choices=[('hackathon', '💻 Hackathon 24H (Projet imposé)'), ('pitch', '💡 Concours Pitch Innovation (Projet libre)'), ('sport', '⚽ Sportive (Football, Basketball, Handball...)'), ('gaming', '🎮 E-Sport / Gaming'), ('other', 'Autre')], default='computer', max_length=20, verbose_name='Type'),
        ),
    ]
