# Generated by Django 4.2.30 on 2026-10-08 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_alter_juincompetition_comp_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubcommission',
            options={'ordering': ['name'], 'verbose_name': 'Commission du Club', 'verbose_name_plural': 'Commissions du Club'},
        ),
        migrations.AlterModelOptions(
            name='clubcommissionapplication',
            options={'ordering': ['-created_at'], 'verbose_name': 'Candidature Commission Club', 'verbose_name_plural': 'Candidatures Commissions Club'},
        ),
        migrations.AddField(
            model_name='clubcommission',
            name='deputy_director_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Directeur Adjoint'),
        ),
        migrations.AddField(
            model_name='clubcommission',
            name='director_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Directeur'),
        ),
        migrations.AddField(
            model_name='clubcommission',
            name='rapporteur_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Rapporteur'),
        ),
        migrations.AddField(
            model_name='clubcommission',
            name='role',
            field=models.TextField(blank=True, help_text='Rôle, attributions et objectifs de la commission', verbose_name='Rôle et Missions'),
        ),
        migrations.AddField(
            model_name='clubcommission',
            name='supervisor_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Superviseur'),
        ),
        migrations.AlterField(
            model_name='clubcommission',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='clubcommission',
            name='icon',
            field=models.CharField(default='fas fa-users-cog', max_length=255, verbose_name='Icône FontAwesome'),
        ),
        migrations.AlterField(
            model_name='clubcommission',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom de la commission'),
        ),
        migrations.AlterField(
            model_name='clubcommissionapplication',
            name='commission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='main.clubcommission', verbose_name='Commission'),
        ),
        migrations.AlterField(
            model_name='clubcommissionapplication',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='club/applications/', verbose_name='Photo portrait'),
        ),
        migrations.AlterField(
            model_name='clubcommissionapplication',
            name='role_applied',
            field=models.CharField(choices=[('director', 'Directeur'), ('deputy_director', 'Directeur Adjoint'), ('rapporteur', 'Rapporteur'), ('deputy_rapporteur', 'Rapporteur Adjoint'), ('supervisor', 'Superviseur'), ('member', 'Membre')], default='member', max_length=30, verbose_name='Poste souhaité'),
        ),
    ]
