# Generated by Django 4.2.30 on 2026-10-09 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_alter_clubcommission_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees_count',
            field=models.PositiveIntegerField(blank=True, help_text="Nombre effectif de participants ayant assisté à l'activité", null=True, verbose_name='Nombre réel de participants'),
        ),
        migrations.AddField(
            model_name='event',
            name='custom_registered_count',
            field=models.PositiveIntegerField(blank=True, help_text="Permet à l'administrateur de modifier ou surcharger le nombre d'inscrits affiché", null=True, verbose_name="Nombre d'inscrits personnalisé"),
        ),
        migrations.AddField(
            model_name='gallery',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_media', to='main.event', verbose_name='Événement associé'),
        ),
    ]
