# Generated by Django 4.2.30 on 2026-10-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_event_attendees_count_event_custom_registered_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.CharField(max_length=200, verbose_name='Nom et prénom du donateur')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Adresse email')),
                ('telephone', models.CharField(max_length=30, verbose_name='Numéro Mobile Money (MTN / Orange)')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Montant du don (FCFA)')),
                ('message', models.TextField(blank=True, verbose_name='Message de soutien')),
                ('is_public', models.BooleanField(default=True, help_text="Si décoché, votre don apparaîtra comme 'Donateur Anonyme'", verbose_name="Afficher mon don publiquement dans l'historique")),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Paiement confirmé')),
                ('date_don', models.DateTimeField(auto_now_add=True, verbose_name='Date du don')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de confirmation')),
                ('freemopay_reference', models.CharField(blank=True, max_length=200, verbose_name='Référence FreemoPay')),
                ('payment_status', models.CharField(choices=[('pending', 'En attente'), ('initiated', 'Initié'), ('completed', 'Confirmé'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut du paiement')),
                ('external_id', models.CharField(max_length=100, unique=True, verbose_name='ID de transaction')),
            ],
            options={
                'verbose_name': 'Don Association',
                'verbose_name_plural': 'Dons Association',
                'ordering': ['-date_don'],
            },
        ),
    ]
